import { noDependencies, sameTag, tag } from '@softarc/sheriff-core';

export const sheriffConfig = {
  tagging: {
    'src/features/calendar': tag('calendar'),
    'src/features/admin': tag('admin'),
    'src/features/auth': tag('auth'),
    'src/features/bug-report': tag('bug-report'),
    'src/features/my-events': tag('my-events'),
    'src/features/profile': tag('profile'),
    'src/features/team-manager': tag('team-manager'),
    'src/shared/components': tag('components'),
    'src/shared/services': tag('services'),
    'src/shared/stores': tag('stores'),
    'src/shared/utils': tag('utils'),
    'src/data': tag('data'),
    'src/types': tag('types'),
    'src/config': tag('config'),
    'src/router': tag('router'),
    'src/i18n': tag('i18n'),
  },
  depRules: {
    calendar: ['components', 'services', 'stores', 'utils', 'data', 'types'],
    admin: ['components', 'services', 'stores', 'utils', 'data', 'types', 'bug-report'],
    auth: ['components', 'services', 'stores', 'utils', 'data', 'types'],
    'bug-report': ['components', 'stores', 'data', 'types'],
    'my-events': ['components', 'services', 'stores', 'utils', 'types'],
    profile: ['components', 'services', 'stores', 'utils', 'data', 'types', 'config'],
    'team-manager': ['components', 'services', 'stores', 'utils', 'data', 'types'],
    components: ['stores', 'services', 'utils', 'types'],
    services: ['data', 'types'],
    stores: ['services', 'utils', 'types'],
    utils: ['data', 'types', 'config'],
    data: ['types'],
    types: noDependencies,
    config: noDependencies,
    router: ['utils'],
    i18n: noDependencies,
  },
};
